### ISSUE TITLE
Nega Yuki position during her scene

### ISSUE THREAD

**Issue by drache444444** [deviant-dev/ds-issues#14]
**Describe the bug**
Nega Yuki is standing on/in my legs/genitalia

![20200201130918_1](https://user-images.githubusercontent.com/60501223/73597913-bd4ee600-4531-11ea-87a5-c2d16bff28bc.jpg)

**Comment by HeadphoneTaco** [comment]
Issue is still occurring in current Master branch (Ver 2.0.8)

**Comment by HeadphoneTaco** [comment]
Issue still occurring in Ver 2.1.0

Seems to be due to nega's crotch lining up with the player's cock; and the way the current animations are set up. May need to make new animations with offset; so as to have Nega standing off to the side of the player, then have her step over and mount on the player.

**Comment by HeadphoneTaco** [comment]
Closing due to age
