### ISSUE TITLE
Yuki thinks player is distracted when not - Yuki reward scene

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#99]
Reported by elvis812 #1664 (Rockanrolla)

**Describe the bug**
   During the Mistress Yuki Reward in the middle of the milking, apropos of nothing, she suddenly stood up and acted as if I was distracted. She scolded me for not paying attention then she asked if I wanted to keep going. The issue is that she never asked in the first place.

**To Reproduce**
 - Playing through the Mistress Yuki reward scene

**Expected behavior**
 - For Yuki not to chide the player for being distracted when they are not distracted

**Screenshots**
  N/A

**System (please complete the following information):**
 - VR Device: N/A
 - Version: 2.0.2

**Additional context**
 - bug to be tested for duplication

**Comment by rockanrolla** [comment]
To be clear, the issue was that she was supposed to be ask “Do you want to keep going?” but she never asked the question at all and then chastised me for not answering the question she never asked. So, I think the solution would be to make sure the audio for her asking the question is in place. Does that make sense?

**Comment by DevilishDomina** [comment]
This may have been fixed in build v 2.0.3. There are no [distracted] commands when a player is supposed to be posing. There is no line in the script where the player is asked if they want to keep going.

There is a line that said, 'do you want to stop?', which I think some players interpreted as 'do you want to keep going?'. To avoid further confusion, I have since replaced the question with 'do you want to keep going.

There is a bug where being in [puppy_back] pose the game won't register yes / no answers, which we are working on now. 

If this bug still exists, can I get log of the play session or a more detailed list of the events as they happened?

**Comment by HeadphoneTaco** [comment]
This bug seems to be resolved, but I only tested in the editor, and not in full VR setup. Leaving open for now.

**Comment by HeadphoneTaco** [comment]
Keeping report open, as status of bug is unknown

**Comment by HeadphoneTaco** [comment]
Closing, as this issue is old, and likely resolved in newer builds
